name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r function/requirements.txt

      - name: Run tests
        run: |
          export PYTHONPATH=$PYTHONPATH:$GITHUB_WORKSPACE
          python -m unittest tests/test_validacao_cpf.py